config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  get '/home', to: 'pages#home'

  
  resources :recipes do
	  member do
		  post 'like'
	  end
	  resources :reviews
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  #resources :reviews, only: [:new, :create, :show]
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :chef
    has_many :likes, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :recipe_styles, dependent: :destroy
    has_many :styles, through: :recipe_styles
    has_many :recipe_ingredients, dependent: :destroy
    has_many :ingredients, through: :recipe_ingredients
    
    validates :chef_id, presence: true
    validates :name, presence: true, length: {minimum:5,maximum:100}
    validates :summary, presence: true, length: {minimum:10,maximum:150}
    validates :description, presence: true, length: {minimum:20,maximum:500}
    mount_uploader :picture, PictureUploader
    validate :picture_size
    default_scope -> {order(updated_at: :desc)}
    
    def thumbs_up_total
        self.likes.where(like: true).size
    end
    
    def thumbs_down_total
        self.likes.where(like: false).size
    end
        
    private
    def picture_size
        if picture.size > 5.megabytes
            errors.add(:picture, "should be less than 5MB")
        end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   
   before_action :set_recipe, only: [:edit, :update, :show, :like, :review]  
   before_action :require_user, except: [:show, :index, :like, :review]
   before_action :require_user_like, only: [:like]
   before_action :require_user_review, only: [:review]
   before_action :require_same_user, only: [:edit, :update]
   before_action :admin_user, only: [:destroy]
   
   def index
       @recipes = Recipe.paginate(page: params[:page], per_page: 4)
   end
   
   def show
		@review = Review.new
	end
   
   def new
      @recipe = Recipe.new
   end
   
   def create
      @recipe = Recipe.new(recipe_params)
      @recipe.chef = current_user
      
      if @recipe.save
         flash[:success] = "Your recipe was created succcesfully!"
         redirect_to recipes_path
      else
         render :new
      end
   end
   
   def edit
   end
   
   def update
      if @recipe.update(recipe_params)
         flash[:success] = "Your recipe was updated succesfully!"
         redirect_to recipe_path(@recipe)
      else
         render :edit
      end
   end
   
   def like
      
      like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
      if like.valid? 
          flash[:success] = "Your selection was succesfull"
          redirect_to :back
      else
          flash[:danger] = "You can only like/dislike a recipe once"
          redirect_to :back
      end
   end
   
   def review
      
      review = Review.create(body: params[:body], chef: current_user, recipe: @recipe)
      if review.valid? 
          flash[:success] = "Your selection was succesfull"
          redirect_to :back
      else
          flash[:danger] = "You can only like/dislike a recipe once"
          redirect_to :back
      end
   end
   
   def destroy
      
      Recipe.find(params[:id]).destroy
      flash[:success] = "Recipe deleted!"
      redirect_to recipes_path
      
   end
   
   private
   
      def recipe_params
         params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids:[], ingredient_ids:[])
      end
      
      def set_recipe
         @recipe = Recipe.find(params[:id])
      end
      
      def require_same_user
         if current_user != @recipe.chef and !current_user.admin?
               flash[:danger] = "You can only edit your own recipes "
               redirect_to recipes_path
         end
      end
      
      def require_user_like
       if !logged_in?
         flash[:danger] = "You must be logged in to perform that action"
         redirect_to :back
       end
      end
      
      def require_user_review
       if !logged_in?
         flash[:danger] = "You must be logged in to perform that action"
         redirect_to :back
       end
      end
      
      def admin_user
         redirect_to recipes_apth unless current_user.admin?
      end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for(@recipe,html: {multipart: true}) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :summary %>
            <%= f.text_field :summary %>
            
            <%= f.label :description %>
            <%= f.text_area :description, rows:10 %>
            
            <strong>Styles:</strong>
            <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
            <br><br>
            <strong>Ingredients:</strong>
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
                <% cbi.label(class: "checkbox-inline input_checkbox") {cbi.check_box(class: "checkbox") + cbi.text} %>
            <% end %>
            <br><br>
            <span class="picture">
                <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
            </span>
            
            <%= f.submit(@recipe.new_record? ? 'Create recipe' : 'Edit recipe', class: "btn btn-success")%>
        <% end %>
    </div>
</div>

<script type="text/javascript">
    $('#recipe_picture').bind('change',function(){
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert ('Maximum file size is 5MB. Please choose a smaller file');
        }
    });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'Edit recipe' %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: 'All recipes' %>

<ul class="nav nav-tabs">
    <li class="active">
        <%= link_to "Recipes", recipes_path %>
    </li>
    <li class="">
        <%= link_to "Chefs", chefs_path %>
    </li>
</ul>


<%= will_paginate %>

<% @recipes.each do |recipe| %>
    <div class="row">
        <div class="col-lg-2">
            <section>
                <h1><span style="font-size:100px" class="glyphicon glyphicon-user" aria-hidden="true"></span></p></h1>
                <%= link_to(chef_path(recipe.chef)) do %>
                  <p style="text-align:center"><%= recipe.chef.chefname %></p>
                <% end %>
            </section>
        </div>
        
        <div class="col-lg-6 well">
        
            <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
            <p><%= recipe.summary%></p>
            <% if recipe.styles.any? %>
                <p>Styles: <%= render recipe.styles %></p>
            <% end %>
            <% if recipe.ingredients.any? %>
                <p>Ingredients: <%= render recipe.ingredients %></p>
            <% end %>
            <p>
                <span class="quiet"><small>created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
                <span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
            </p>
            <div class="pull-right">
                <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
                <% end %> &nbsp&nbsp&nbsp&nbsp
                <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
                <% end %>
            </div>
        </div>
        
        <div class="col-md-4">
            <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
        </div>
        
        
    </div>
    <hr/>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: 'Create recipe' %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<br/><br/>
<h5>
<%= link_to "Return to recipes listing", recipes_path, class:"btn btn-sm btn-default"%>
<%= link_to "Back to chef", chef_path(@recipe.chef), class: "btn btn-sm btn-default" %>
<% if logged_in? and (@recipe.chef == current_user) || current_user.admin? %>
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-sm btn-default" %>
<% end %>
<% if logged_in? and current_user.admin? %>
    <%= link_to "Delete recipe", @recipe, method: :delete, class: "btn btn-sm btn-default", data: {confirm: "Are you sure?"} %>
<% end %>
</h5>
<div class="row">
    <div class="col-md-4 pull-right center">
        <section>
                <p style="font-size: 100px"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></p>
        </section>
        
        <p>
            <h5>
                Brought to you by: <%=@recipe.chef.chefname%>
            </h5>
        </p>
        
    </div>
    <div class="col-md-8">

        <h3><%=@recipe.summary%></h3>
        <div class="show_recipe">
            <%= image_tag(@recipe.picture.url,class:"gravatar") if @recipe.picture? %>
        </div>
        <div class="well">
            <% if @recipe.styles.any? %>
            <p>Styles: <%= render @recipe.styles %></p>
            <% end %>
            <% if @recipe.ingredients.any? %>
            <p>Ingredients: <%= render @recipe.ingredients %></p>
            <% end %>
            <p>
                <strong>Steps:</strong>
            </p>

            <%= simple_format(@recipe.description) %>
               
            <div class="pull-right">
                <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= @recipe.thumbs_up_total %>
                <% end %>&nbsp&nbsp&nbsp&nbsp
                <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= @recipe.thumbs_down_total %>
                <% end %>
            </div>
            
            
        </div>
        
        <% if logged_in? %>
        
        <div id="well_review" class="well">
            <p>Create review</p>
            <%= form_for([@recipe, @review]) do |f| %>
            
                <%= f.label :Review %>
                <%= f.text_area :body, rows:7 %>
            
                <%= f.submit('Create review', class: "btn btn-success")%>
            <% end %>
        </div>        
        <% end %>
        
        <% if @recipe.reviews.any? %>
            <p>Reviews:</p>
            <% @recipe.reviews.each do |review| %>
                <div class="well">
                    <p>Chef <%= review.chef.chefname %> says:</p>
                    <p><%= review.body %></p>
                </div>
            <% end %>
        <% end %>
    </div>
</div>