config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  get '/home', to: 'pages#home'

  
  resources :recipes do
	  member do
		  post 'like'
	  end
	  resources :reviews
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  #resources :reviews, only: [:new, :create, :show]
end

app/views/pages/home.html.erb
<div class="row">
    
    <div class="col-lg-4 center">
      <%= link_to (recipes_path) do %>
        <img style="box-shadow: 10px 10px 5px #ccc;" src="https://cdn3.iconfinder.com/data/icons/humano2/72x72/mimetypes/type-list.png">
      <% end %>
      <h3 class="midrow">View recipes as guest user</h3>
      <h5 class="">Browse and view recipes and sign up later</h5>
      
    </div>
    
    <div class="col-lg-4 center">
      <%= link_to (login_path) do %>
        <img style="box-shadow: 10px 10px 5px #ccc;" src="https://cdn3.iconfinder.com/data/icons/humano2/72x72/emblems/emblem-people.png">
      <% end %>
      
      <h3 class="midrow">Sign in to your account</h3>
      <h5 class="">Add/update recipes and much more</h5>
      
    </div>
    
    <div class="col-lg-4 center">
      <%= link_to (register_path) do %>
        <img style="box-shadow: 10px 10px 5px #ccc;" src="https://cdn2.iconfinder.com/data/icons/humano2/72x72/actions/contact-new.png">
      <% end %>
      
      <h3 class="midrow">Register new Chef</h3>
      <h5 class="">Sign up</h5>
      
    </div>
    
  </div>