config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  get '/home', to: 'pages#home'

  
  resources :recipes do
	  member do
		  post 'like'
	  end
	  resources :reviews
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  #resources :reviews, only: [:new, :create, :show]
end

app/models/style.rb
class Style < ActiveRecord::Base
    validates :name, presence: true, length: {minimum:2, maximum:25}
    has_many :recipe_styles
    has_many :recipes, through: :recipe_styles
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
    
    before_action :require_user, except: [:show]
    
    def show
        @style = Style.find(params[:id])
        @recipes = @style.recipes.paginate(page: params[:page], per_page: 4)
    end

    def new
        @style = Style.new
    end
    
    def create
        @style = Style.new(style_params)
        if @style.save
            flash[:success] = "Style was created successfully"
            redirect_to recipes_path
        else
            render 'new'
        end
    end
    
    private
        def style_params
            params.require(:style).permit(:name)
    
        end
end

app/views/styles/_style.html.erb
<span class="quiet"><%= link_to style.name, style_path(style) %> </span>

app/views/styles/new.html.erb
<%= render 'shared/page_title', title: 'Create a new style' %>

<%= render 'shared/errors', obj: @style %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @style do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            <br/>
            <br/>
            <%= f.submit 'Create Style', class: "btn btn-success"%>
        <% end %>
    </div>
</div>

app/views/styles/show.html.erb
<%= render 'shared/page_title', title: "Recipes for style " + @style.name %>

<ul class="nav nav-tabs">
    <li class="active">
        <%= link_to "Recipes", recipes_path %>
    </li>
    <li class="">
        <%= link_to "Chefs", chefs_path %>
    </li>
</ul>


<%= will_paginate @recipes %>

<% @style.recipes.each do |recipe| %>
    <div class="row">
        <div class="col-lg-2">
            <section>
                <h1><span style="font-size:100px" class="glyphicon glyphicon-user" aria-hidden="true"></span></p></h1>
                <%= link_to(chef_path(recipe.chef)) do %>
                  <p style="text-align:center"><%= recipe.chef.chefname %></p>
                <% end %>
            </section>
        </div>
        
        <div class="col-lg-6 well">
        
            <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
            <p><%= recipe.summary%></p>
            <p>Styles: <%= render recipe.styles %></p>
            <p>Ingredients: <%= render recipe.ingredients %></p>
            <p>
                <span class="quiet"><small>created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
                <span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
            </p>
            <div class="pull-right">
                <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
                <% end %> &nbsp&nbsp&nbsp&nbsp
                <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
                <% end %>
            </div>
        </div>
        
        <div class="col-md-4">
            <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
        </div>
        
        
    </div>
    <hr/>
<% end %>

<%= will_paginate @recipes %>