config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  
  get '/home', to: 'pages#home'

  
  resources :recipes do
	  member do
		  post 'like'
	  end
	  resources :reviews
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  #resources :reviews, only: [:new, :create, :show]
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <p>&copy; My.Recipes 2015</p>
    <p>This project was done by Ricardo Maduro while learning Udemy Professional Ruby on Rails course</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-md-12">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%=message_type%>">
                <%= message %>
                <a class="close" data-dismiss="alert">&#215;</a>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default navbar-right">
    <div class="container">
      <%=link_to (image_tag("https://cdn4.iconfinder.com/data/icons/X-Mac/education_icons/png/64/teachers_day.png")) + "Recipes on Rails", root_path, style:"color:black; font-size: 15px", id: "logo"%>
      
      <div class="nav_ul_item">
        <li class="dropdown">
          <%= link_to '#', class:"btn btn-sm btn-default dropdown-toggle", "data-toggle" => "dropdown" do %>
            Styles <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% Style.all.each do |style| %>
              <li><%= link_to style.name, style_path(style) %></li>
            <% end %>
            <% if logged_in? %>
            <li class='divider'></li>
            <li>
              <%= link_to(new_style_path) do %>
                New style
              <% end %>
            </li>
            <% end %>
          </ul>
        </li>
      </div>
      <div class="nav_ul_item">
        <li class="dropdown">
          <%= link_to '#', class:"btn btn-sm btn-default dropdown-toggle", "data-toggle" => "dropdown" do %>
            Ingredients <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% Ingredient.all.each do |ing| %>
              <li><%= link_to ing.name, ingredient_path(ing) %></li>
            <% end %>
            <% if logged_in? %>
            <li class='divider'></li>
            <li>
              <%= link_to(new_ingredient_path) do %>
                New ingredient
              <% end %>
            </li>
            <% end %>
          </ul>
        </li>
      </div>
      
      <% if logged_in? %>
        <ul class="nav-item pull-right" style="margin-top:40px; list-style-type:none">
          <li class="dropdown">
            <%= link_to '#', class:"btn btn-sm btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
              <%= current_user.chefname %> <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to "View my recipes", chef_path(current_user) %></li>
              <li><%= link_to "Edit profile", edit_chef_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", logout_path %></li>
            </ul>
          </li>
        </ul>
        <div class="nav-item" style="margin-top:40px">
          <%=link_to "New recipe",new_recipe_path,class: "btn btn-sm btn-default"%>
        </div>
      <% else %>
        <div class="nav-item pull-right" style="margin-top:40px">
          <%=link_to "Login",login_path,class: "btn btn-sm btn-success"%>
        </div>
      <% end %>
        
      
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipesOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body background-color:white>
  
  <%= render "layouts/navigation" %>
  
  <div style="background-size:100%;
              background-image:linear-gradient(rgba(0, 0, 0, 0.4),rgba(0, 0, 0, 0.4)), 
					    url(https://download.unsplash.com/reserve/fPuLkQNXRUKI6HQ2cMPf_IMG_4761.jpg); 
					    height: 360px; width: 100%;">
    
    <div class="row" style="font-color:white margin-top: 60px;">
      <div class="col-md-12">
        <h1 style="position: absolute; 
                   top: 150px; 
                   left: 0; 
                   width: 100%;
                   font: bold 50px Helvetica; 
                   color: white;
                   text-shadow: 3px 3px black;" >
                  What do you want to eat today?
        </h1>
      </div>  
    </div>
    
    
    
  </div>
  <div class="container" style="margin-top:30px">
    <%= render "layouts/messages" %>
    <%= yield %>
  </div>

  <%=render "layouts/footer"%>
  
</body>
</html>
                                              